import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FontAwesomeScript from "./FontAwesomeScript";
import Footer from "@/UI/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MK Exports",
  description: "Generated by MK Exports",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{margin:0}}>
  
              <main style={{margin:"0"}}>{children}</main>
        <Footer />
        <FontAwesomeScript />
      </body>
    </html>
  );
}
